-- Phone verification (email OTP) for delivery contact
ALTER TABLE User ADD COLUMN phoneVerifiedAt DATETIME;

CREATE TABLE IF NOT EXISTS PhoneOtp (
  id TEXT PRIMARY KEY NOT NULL,
  userId TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL,
  codeHash TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  expiresAt DATETIME NOT NULL,
  lastSentAt DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS PhoneOtp_phone_idx ON PhoneOtp(phone);
