INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvkx0003gc72suz5ujyi','PLIX Rosemary Hair Growth Serum','plix-rosemary-hair-growth-serum','Potent rosemary-infused hair serum that nourishes the scalp and supports visibly denser-looking hair.','Plix','50ml',699,499,29,'PLIX-RHS-50',42,'Hair Serum','["Promotes healthier scalp","Lightweight non-greasy formula","Enriched with botanical oils"]','Rosmarinus Officinalis Leaf Oil, Caprylic Triglyceride, Tocopherol.','Apply 3–4 drops on scalp nightly. Massage gently. Do not rinse.','["/products/hair-oil-bottle.jpg","/products/dropper-serum.jpg"]',4.6,128,0,'2026-08-29T17:38:49.377Z','2026-08-29T17:38:49.377Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvl80004gc72bv3xicia','PLIX Pomegranate Youth Renewal Serum','plix-pomegranate-youth-renewal-serum','Antioxidant-rich pomegranate serum for glowing, youthful-looking skin.','Plix','30ml',899,649,28,'PLIX-PYR-30',35,'Face Essential','["Brightens dull skin","Hydrates deeply","Supports collagen look"]','Punica Granatum Extract, Niacinamide, Hyaluronic Acid.','Apply 2–3 drops morning and night after cleansing.','["/products/vitamin-c-serum.jpg","/products/dropper-serum.jpg"]',4.7,96,0,'2026-08-29T17:38:49.388Z','2026-08-29T17:38:49.388Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvlj0005gc7210iy7ocv','PLIX Guava Glow Night Cream','plix-guava-glow-night-cream','Overnight guava cream that restores radiance while you sleep.','Plix','50g',799,549,31,'PLIX-GGN-50',28,'Night Cream','["Overnight repair","Softens texture","Locks in moisture"]','Psidium Guajava Extract, Shea Butter, Glycerin.','Massage onto face and neck as the last step of your night routine.','["/products/pink-cream-jar.jpg","/products/night-cream-jar.jpg"]',4.5,74,0,'2026-08-29T17:38:49.400Z','2026-08-29T17:38:49.400Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvlx0006gc72mgyj2kpw','Pilgrim 2% Salicylic Acid Face Wash','pilgrim-salicylic-acid-face-wash','Gentle clarifying face wash with 2% salicylic acid for clearer-looking skin.','Pilgrim','100ml',450,349,22,'PIL-SAFW-100',60,'Face Essential','["Unclogs pores","Controls excess oil","Fresh clean finish"]','Salicylic Acid 2%, Aloe Vera, Glycerin.','Lather on damp face, massage 30 seconds, rinse. Use AM/PM.','["/products/face-wash-tube.jpg"]',4.4,210,0,'2026-08-29T17:38:49.413Z','2026-08-29T17:38:49.413Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvma0007gc721an33kue','Pilgrim Hair Growth Oil','pilgrim-hair-growth-oil','Botanical hair oil blend to strengthen strands and soothe the scalp.','Pilgrim','100ml',650,499,23,'PIL-HGO-100',40,'Hair Serum','["Reduces breakage look","Nourishes scalp","Adds natural shine"]','Bhringraj, Amla, Coconut Oil, Rosemary.','Warm a few drops, massage into scalp, leave overnight, wash next day.','["/products/hair-oil-bottle.jpg","/products/dropper-serum.jpg"]',4.3,155,0,'2026-08-29T17:38:49.426Z','2026-08-29T17:38:49.426Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvmm0008gc72kx9ya8ma','Mamaearth Rice Water Face Wash','mamaearth-rice-water-face-wash','Mild rice water cleanser for soft, glass-skin feel.','Mamaearth','100ml',399,299,25,'ME-RWF-100',80,'Face Essential','["Gentle daily cleanse","Toxins-free formula","Suitable for most skin types"]','Oryza Sativa (Rice) Water, Aloe Barbadensis.','Use morning and night. Avoid eye area.','["/products/face-wash-tube.jpg","/products/botanical-serum.jpg"]',4.5,320,0,'2026-08-29T17:38:49.439Z','2026-08-29T17:38:49.439Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvmz0009gc729246k82w','Dr. Rashel Vitamin C Night Cream','dr-rashel-vitamin-c-night-cream','Vitamin C night cream for a brighter morning complexion.','Dr. Rashel','50g',999,699,30,'DR-VCNC-50',22,'Night Cream','["Boosts glow","Hydrating cream base","Night recovery"]','Ascorbic Acid, Shea Butter, Vitamin E.','Apply a pea-sized amount at night after serum.','["/products/night-cream-jar.jpg","/products/pink-cream-jar.jpg"]',4.2,88,0,'2026-08-29T17:38:49.452Z','2026-08-29T17:38:49.452Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvne000agc72ekkauu7g','Dr. Rashel Hyaluronic Acid Face Serum','dr-rashel-hyaluronic-acid-face-serum','Multi-weight hyaluronic serum for plump, dewy skin.','Dr. Rashel','30ml',899,599,33,'DR-HAFS-30',33,'Face Essential','["Intense hydration","Plumping effect","Layers under moisturizer"]','Sodium Hyaluronate, Panthenol, Allantoin.','Apply on damp skin AM/PM before cream.','["/products/dropper-serum.jpg","/products/botanical-serum.jpg"]',4.6,141,0,'2026-08-29T17:38:49.467Z','2026-08-29T17:38:49.467Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvns000bgc72aamlbnoc','Biotique Bio Coconut Whitening Cream','biotique-bio-coconut-cream','Ayurvedic coconut cream for nourished, even-toned skin.','Biotique','50g',299,249,17,'BIO-BCC-50',55,'Night Cream','["Ayurvedic formula","Deep nourishment","Soft finish"]','Cocos Nucifera Oil, Ayurvedic extracts.','Apply nightly on cleansed face.','["/products/clay-mask-jar.jpg","/products/night-cream-jar.jpg"]',4.1,190,0,'2026-08-29T17:38:49.481Z','2026-08-29T17:38:49.481Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvo5000cgc72wwn1v3ui','Dot & Key Night Reset Retinol Cream','dot-key-night-reset-retinol-cream','Encapsulated retinol night cream for smoother-looking skin.','Dot & Key','60ml',845,695,18,'DK-NRR-60',18,'Night Cream','["Smooths fine lines look","Barrier-friendly","Night reset ritual"]','Retinol, Ceramides, Niacinamide.','Use 2–3 nights a week. Always pair with SPF in the morning.','["/products/pink-cream-jar.jpg","/products/clay-mask-jar.jpg"]',4.8,260,0,'2026-08-29T17:38:49.494Z','2026-08-29T17:38:49.494Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvol000dgc72w8a9u13e','Alpainoo Botanical Glow Face Serum','alpainoo-botanical-glow-face-serum','Signature botanical serum with jojoba, vitamin E, and aloe for natural radiance.','Alpainoo','30ml',1299,899,31,'EK-BGFS-30',50,'Face Essential','["Natural radiance booster with Jojoba Oil, Vitamin E, and Aloe Vera","Hydrates and illuminates all skin types","Cruelty-free and vegan"]','Simmondsia Chinensis (Jojoba) Seed Oil, Tocopherol (Vitamin E), Aloe Barbadensis Leaf Juice.','Press 2–3 drops onto face after cleansing. Follow with moisturizer.','["/products/botanical-serum.jpg","/products/dropper-serum.jpg"]',4.9,64,0,'2026-08-29T17:38:49.509Z','2026-08-29T17:38:49.509Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvow000egc72dclotm7u','Alpainoo Mist Bloom Eau de Parfum','alpainoo-mist-bloom-edp','Soft floral fragrance with notes of peony, bergamot, and warm musk.','Alpainoo','50ml',1899,1499,21,'EK-MB-50',25,'Perfume','["Long-lasting trail","Unisex soft floral","Travel-friendly bottle"]','Alcohol Denat., Parfum, Linalool, Limonene.','Spray on pulse points. Avoid rubbing.','["/products/perfume-bottle.jpg"]',4.7,52,0,'2026-08-29T17:38:49.521Z','2026-08-29T17:38:49.521Z');
INSERT OR REPLACE INTO Product (id,title,slug,description,brand,volume,mrp,sellingPrice,discount,sku,stock,category,benefits,ingredients,usage,images,rating,reviewCount,isHidden,createdAt,updatedAt) VALUES ('cmtenzvp7000fgc7239ftyy04','Mamaearth Onion Hair Serum','mamaearth-onion-hair-serum','Onion seed oil serum for smoother, frizz-controlled hair.','Mamaearth','100ml',449,349,22,'ME-OHS-100',8,'Hair Serum','["Frizz control","Adds shine","Lightweight"]','Onion Seed Oil, Argan Oil, Vitamin E.','Apply on damp or dry lengths. Style as usual.','["/products/hair-oil-bottle.jpg","/products/vitamin-c-serum.jpg"]',4.3,400,0,'2026-08-29T17:38:49.531Z','2026-08-29T17:38:49.531Z');
INSERT OR REPLACE INTO BlogPost (id,title,slug,excerpt,content,coverImage,tags,published,createdAt,updatedAt) VALUES ('cmtenzvpj000ggc72pxo35cih','The Perfect AM Skincare Routine for Glowing Skin','am-skincare-routine-glowing-skin','Build a simple morning ritual with cleanser, serum, and SPF that actually sticks.','## Start fresh

A glowing complexion starts with consistency. Begin with a gentle cleanser like rice water or salicylic wash depending on your skin type.

## Layer hydration

Serums with hyaluronic acid or botanical oils lock in moisture. Try our **Alpainoo Botanical Glow Face Serum** for daily radiance.

## Seal and protect

Finish with a light moisturizer and broad-spectrum SPF. Never skip sunscreen—even on cloudy days.

### Related tips
- Patch test new actives
- Introduce one product at a time
- Keep routines under 5 steps for better adherence
','/blog/am-routine.jpg','["skincare","routine","serum"]',1,'2026-08-29T17:38:49.543Z','2026-08-29T17:38:49.543Z');
INSERT OR REPLACE INTO BlogPost (id,title,slug,excerpt,content,coverImage,tags,published,createdAt,updatedAt) VALUES ('cmtenzvpu000hgc72xnx0w9el','Best Serums for Glowing Skin in 2026','best-serums-for-glowing-skin','From vitamin C to rosemary scalp serums—our editor picks for every concern.','## Why serums win

Serums deliver concentrated actives that creams alone cannot. Choose by concern: brightening, hydration, or scalp health.

## Our top picks
1. **Botanical Glow Face Serum** — jojoba + vitamin E
2. **PLIX Pomegranate Youth Renewal** — antioxidants
3. **Dr. Rashel HA Serum** — deep hydration

Pair with a compatible moisturizer and you will notice a healthier-looking glow within weeks.
','/blog/serums-guide.jpg','["serum","guide","face"]',1,'2026-08-29T17:38:49.555Z','2026-08-29T17:38:49.555Z');
INSERT OR REPLACE INTO BlogPost (id,title,slug,excerpt,content,coverImage,tags,published,createdAt,updatedAt) VALUES ('cmtenzvq5000igc726yuycjqd','Haircare Guide: Serums, Oils & Scalp Care','haircare-guide-serums-oils','How to combine rosemary serum, growth oils, and weekly rituals for stronger-looking hair.','## Scalp first

Healthy-looking hair begins at the scalp. Massage rosemary serum nightly and alternate with a nourishing oil once a week.

## Lengths care

Apply lightweight onion or argan serum on mid-lengths to tame frizz without weighing hair down.

## Weekly reset
- Clarify once a week if you use heavy oils
- Protect with heat protectant before styling
- Trim split ends every 8–10 weeks
','/blog/haircare.jpg','["haircare","serum","routine"]',1,'2026-08-29T17:38:49.565Z','2026-08-29T17:38:49.565Z');
INSERT OR REPLACE INTO KnowledgeArticle (id,slug,title,question,answer,keywords,category,active,createdAt,updatedAt) VALUES ('cmtenzvqf000jgc72l1i9fym0','shipping-times','Shipping times','How long does shipping take?','Orders are typically processed within 1–2 business days. Delivery across India usually takes 3–7 business days depending on your pincode. You will receive tracking details by email once the courier picks up your parcel.','["shipping","delivery","how long","days","courier","dispatch"]','SHIPPING',1,'2026-08-29T17:38:49.575Z','2026-08-29T17:38:49.575Z');
INSERT OR REPLACE INTO KnowledgeArticle (id,slug,title,question,answer,keywords,category,active,createdAt,updatedAt) VALUES ('cmtenzvqq000kgc72ehokvxg5','track-order','Track an order','How do I track my order?','Sign in to your account and ask the chat assistant about your order, or check the shipping confirmation email for the AWB / tracking link. Tracking appears after the order status moves to SHIPPED.','["track","tracking","awb","where is my order","shipment"]','SHIPPING',1,'2026-08-29T17:38:49.587Z','2026-08-29T17:38:49.587Z');
INSERT OR REPLACE INTO KnowledgeArticle (id,slug,title,question,answer,keywords,category,active,createdAt,updatedAt) VALUES ('cmtenzvr1000lgc72575mrsak','returns-policy','Returns & exchanges','What is your return policy?','Unopened products in original packaging may be eligible for return or exchange within 7 days of delivery. Opened skincare items generally cannot be returned for hygiene reasons. Contact support with your order number to start a request.','["return","refund","exchange","policy","damaged"]','RETURNS',1,'2026-08-29T17:38:49.597Z','2026-08-29T17:38:49.597Z');
INSERT OR REPLACE INTO KnowledgeArticle (id,slug,title,question,answer,keywords,category,active,createdAt,updatedAt) VALUES ('cmtenzvrc000mgc72flw7c2vv','payment-methods','Payment methods','What payment methods do you accept?','We accept secure online payments via Razorpay (UPI, cards, netbanking, and supported wallets). Cash on delivery may not be available for all pincodes.','["payment","razorpay","upi","card","cod","pay"]','PAYMENT',1,'2026-08-29T17:38:49.608Z','2026-08-29T17:38:49.608Z');
INSERT OR REPLACE INTO KnowledgeArticle (id,slug,title,question,answer,keywords,category,active,createdAt,updatedAt) VALUES ('cmtenzvrm000ngc72pymmvfdx','cancel-order','Cancel an order','Can I cancel my order?','You can request cancellation from your order page while the order is still PENDING, PAID, or PROCESSING (before it ships). Once shipped, please wait for delivery and use the returns process if eligible.','["cancel","cancellation","stop order"]','ORDERS',1,'2026-08-29T17:38:49.619Z','2026-08-29T17:38:49.619Z');
INSERT OR REPLACE INTO KnowledgeArticle (id,slug,title,question,answer,keywords,category,active,createdAt,updatedAt) VALUES ('cmtenzvrx000ogc72nlxsfmmz','contact-support','Contact support','How do I contact Alpainoo support?','Use this chat for quick help, or email contactus@alpainoo.com. For unresolved issues, create a support ticket from chat and our team will reply within the stated turnaround time.','["contact","email","support","help","phone"]','SUPPORT',1,'2026-08-29T17:38:49.629Z','2026-08-29T17:38:49.629Z');
INSERT OR REPLACE INTO KnowledgeArticle (id,slug,title,question,answer,keywords,category,active,createdAt,updatedAt) VALUES ('cmtenzvs7000pgc72cq1qsjgm','ingredients-safety','Ingredients & safety','Are your products safe / natural?','Alpainoo focuses on botanical-forward formulas. Each product page lists key ingredients, benefits, and usage. If you have allergies, review the ingredients list carefully or ask us about a specific product before purchasing.','["ingredients","natural","organic","safe","allergy","botanical"]','PRODUCT',1,'2026-08-29T17:38:49.639Z','2026-08-29T17:38:49.639Z');
INSERT OR REPLACE INTO KnowledgeArticle (id,slug,title,question,answer,keywords,category,active,createdAt,updatedAt) VALUES ('cmtenzvsh000qgc72iwk78zcv','stock-availability','Stock availability','How do I know if a product is in stock?','Product pages and the shop catalog show live stock. Out-of-stock items cannot be added to cart. You can also ask this chat about a product name and we will check availability.','["stock","available","out of stock","inventory"]','PRODUCT',1,'2026-08-29T17:38:49.649Z','2026-08-29T17:38:49.649Z');
INSERT OR REPLACE INTO KnowledgeArticle (id,slug,title,question,answer,keywords,category,active,createdAt,updatedAt) VALUES ('cmtenzvsr000rgc723vem0vn6','account-login','Account & login','Do I need an account?','You can browse without an account. Sign in with Google to view your personal order history, request cancellations, and get order-specific help from this assistant.','["account","login","sign in","google","profile"]','ACCOUNT',1,'2026-08-29T17:38:49.659Z','2026-08-29T17:38:49.659Z');
INSERT OR REPLACE INTO KnowledgeArticle (id,slug,title,question,answer,keywords,category,active,createdAt,updatedAt) VALUES ('cmtenzvt1000sgc72m4rd0mvr','tat-tickets','Support ticket TAT','How fast will you reply to a ticket?','General support tickets have a 24-hour turnaround target. Order-related tickets have a 48-hour turnaround target. You will receive a ticket number when a ticket is created from chat.','["tat","ticket","response time","sla","how fast"]','SUPPORT',1,'2026-08-29T17:38:49.670Z','2026-08-29T17:38:49.670Z');